on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: yaml validator
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: json-yaml-validate
        uses: GrantBirki/json-yaml-validate@v2.6.1
        with:
          files: |
            _data/fellows.yaml
            _data/planet.yaml
